version: "3.8"
services:
  api:
    build: ./server
    container_name: api_backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:newPassword@database:5434/dev_it
      - PORT=4000
      - JWT_ACCESS_SECRET=JWT_ACCESS_SECRET
      - JWT_REFRESH_SECRET=JWT_REFRESH_SECRET
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - database
      - client

  database:
    container_name: database
    image: "postgres:12"
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev_it
    volumes:
      - nps_data:/var/lib/postgresql/data
    command: -p 5434

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://localhost:4000
volumes:
  nps_data: {}
